title:   David Stokes
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>

  <br><br><br>
  <a href="">View My LinkedIn Profile</a>
  <br><br>
  <a href="">View My Tableau Work Samples</a>
  <br><br>
  <a href="">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
